name: Build, Test & Release on Push

on:
  push:
    branches:
      - main
jobs:
  angular:
    uses: khumozin/workflow-templates/.github/workflows/angular-build-app.yml@1.10.1
    with:
      node_version: "['24.x']"

  vitest:
    needs: [angular]
    uses: khumozin/workflow-templates/.github/workflows/angular-vitest-app.yml@1.10.1
    with:
      node_version: "['24.x']"

  semantic-release:
    needs: [vitest]
    uses: khumozin/workflow-templates/.github/workflows/nodejs-semantic-release.yml@1.11.0
    with:
      node_version: "24.x"
    secrets:
      release_token: ${{ secrets.RELEASE_TOKEN }}
    permissions:
      contents: write